// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpvwtfizytwcmyzrlubv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdnd0Zml6eXR3Y215enJsdWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0OTg5NDgsImV4cCI6MjA0NzA3NDk0OH0.S46GzwZD2LE5sy8aVfMXwFp2VfNqwSD3KNpzCXBPHgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);